# docker-compose.yml
version: "3.8"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: sa_hcmus
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: admin
      PGDATA: /data/postgres
    ports:
      - 5435:5432
    volumes:
      - postgres:/data/postgre
    restart: on-failure:3
  pgweb:
    image: sosedoff/pgweb
    depends_on:
      - postgres
    environment:
      PGWEB_DATABASE_URL: postgres://admin:1234@postgres:5432/sa_hcmus?sslmode=disable
    ports:
      - 8085:8081
    restart: on-failure:3
  redis:
    image: redis:latest
    command: redis-server
    volumes:
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    networks:
      - redis-network
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=qwerty
    ports:
      - 8081:8081
    networks:
      - redis-network
    depends_on:
      - redis
volumes:
  postgres:
  redis:
  redis-config:
networks:
  redis-network:
    driver: bridge
